version: '3.7'

services:
  aptos-validator:
    container_name: aptos-validator
    hostname: aptos-validator
    restart: always
    build:
      context: .build
      dockerfile: dev.Dockerfile 
      args:
        NODE_BIN_PATH: ${NODE_BIN_PATH}
    networks:
      shared:
        ipv4_address:  172.16.1.10
    volumes:
      - ./data:/opt/aptos/var
      - ./validator_node_template.yaml:/opt/aptos/var/validator_node_template.yaml
      - ${NODE_BIN_PATH}:/opt/aptos/bin/aptos-node:ro
    command: ["/opt/aptos/bin/aptos-node", "--test", "--config", "/opt/aptos/var/"]
    ports:
      - "8080:8080"
      - "9101:9101"

  aptos-faucet:
    container_name: aptos-faucet
    hostname: aptos-faucet
    restart: always
    build:
      context: .build
      dockerfile: Dockerfile 
      args:
        FAUCET_BIN_PATH: ${FAUCET_BIN_PATH}
    depends_on:
      - aptos-validator
    networks:
      shared:
        ipv4_address:  172.16.1.11
    volumes:
      - ./data:/opt/aptos/var
      - ${FAUCET_BIN_PATH}:/opt/aptos/bin/aptos-faucet:ro
    command: >
      /bin/bash -c "
        for i in {1..10}; do
          if [[ ! -s /opt/aptos/var/mint.key ]]; then
            echo 'Validator has not populated mint.key yet. Is it running?'
            sleep 1
          else
            sleep 1
            /opt/aptos/bin/aptos-faucet \\
              --address 0.0.0.0 \\
              --port 8000 \\
              --chain-id TESTING \\
              --mint-key-file-path /opt/aptos/var/mint.key \\
              --server-url http://172.16.1.10:8080
            echo 'Faucet failed to run likely due to the Validator still starting. Will try again.'
          fi
        done
        exit 1
      "
    ports:
      - "8000:8000"

networks:
  shared:
    name: "aptos-docker-compose-shared"
    ipam:
      config:
        - subnet: 172.16.1.0/24